# -*- coding: utf-8 -*-
"""question-0002-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggtdTpdYdIK6Dz51b0aqC_K3uMS8xOw9

**question-0002-usecase-generator**
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

def generar_caso_de_detect_feature_drift():
    """
    Genera casos de prueba aleatorios para la función detect_feature_drift.
    Crea dos DataFrames (train y test) con distribuciones que pueden o no variar.
    """
    # --- Configuración Aleatoria ---
    n_samples = np.random.randint(100, 500)
    n_features = np.random.randint(2, 6)
    threshold = round(np.random.uniform(0.1, 0.5), 2)

    col_names = [f"feature_{i}" for i in range(n_features)]

    # Generar datos de entrenamiento (Distribución Normal estándar)
    data_train = np.random.randn(n_samples, n_features)
    df_train = pd.DataFrame(data_train, columns=col_names)

    # Generar datos de test y calcular el drift esperado
    data_test = data_train.copy()
    expected_output = {}

    # Aplicar transformaciones aleatorias para simular drift
    for i, col in enumerate(col_names):
        # Decidir aleatoriamente si esta columna tendrá drift (50% probabilidad)
        if np.random.choice([True, False]):
            shift = np.random.uniform(threshold * 2, threshold * 5)
            data_test[:, i] += shift

            # Cálculo simplificado de la métrica (Distancia entre medias tras escalado)
            # Como train es normal (0,1), la diferencia tras escalar es aproximadamente el shift
            expected_output[col] = float(np.abs(shift))

    df_test = pd.DataFrame(data_test, columns=col_names)

    # --- Estructura de Retorno ---
    input_dict = {
        "df_train": df_train,
        "df_test": df_test,
        "threshold": threshold
    }

    # Filtrar el output esperado según el threshold real
    output_dict = {k: v for k, v in expected_output.items() if v > threshold}

    return input_dict, output_dict

# Ejemplo de ejecución:
# input_data, expected_result = generar_caso_de_detect_feature_drift()
# print(f"Threshold: {input_data['threshold']}")
# print(f"Columnas con Drift esperado: {list(expected_result.keys())}")
