# -*- coding: utf-8 -*-
"""question-0001-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggtdTpdYdIK6Dz51b0aqC_K3uMS8xOw9

**question-0001-usecase-generator**
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

def generar_caso_de_detect_drifting_sensors():
    """
    Genera un caso de prueba aleatorio (input y output esperado)
    para la función detect_drifting_sensors.
    """
    # 1. Parámetros aleatorios del escenario
    n_rows = np.random.randint(800, 1200)
    ref_rows = np.random.randint(300, 500)
    n_sensors = np.random.randint(3, 7)
    sensor_names = [f"Sensor_{chr(65+i)}" for i in range(n_sensors)]

    # 2. Generar datos base (normales: media 50, std 5)
    data = np.random.normal(50, 5, (n_rows, n_sensors))
    df = pd.DataFrame(data, columns=sensor_names)

    # 3. Decidir aleatoriamente qué sensores tendrán "drift"
    # Seleccionamos al menos uno para asegurar que el test sea interesante
    n_drifting = np.random.randint(1, n_sensors)
    drifting_cols = np.random.choice(sensor_names, n_drifting, replace=False).tolist()

    expected_output = []

    for col in sensor_names:
        if col in drifting_cols:
            # Aplicamos un desplazamiento fuerte (ej. +4 desviaciones estándar)
            # a más del 15% de los datos finales para asegurar que falle
            start_drift = ref_rows + 1
            # El desplazamiento debe ser suficiente para salir de +/- 3 sigma
            df.loc[start_drift:, col] += 20
            expected_output.append(col)

    # Mezclamos la salida esperada para que no dependa del orden de creación
    expected_output.sort()

    # 4. Formatear el Input
    input_dict = {
        "df": df,
        "ref_rows": ref_rows
    }

    return input_dict, expected_output

# --- Ejemplo de uso ---
input_data, output_esperado = generar_caso_de_detect_drifting_sensors()

print(f"Configuración: {len(input_data['df'])} filas, {input_data['ref_rows']} de referencia.")
print(f"Sensores que deberían fallar: {output_esperado}")
print("\nPrimeras 5 filas del DataFrame:")
print(input_data['df'].head())
