# -*- coding: utf-8 -*-
"""question-0003-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggtdTpdYdIK6Dz51b0aqC_K3uMS8xOw9

**question-0003-usecase-generator**
"""

import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def generar_caso_de_uso_0003():
    """
    Genera casos de prueba aleatorios para la función detect_data_drift.
    Crea un escenario de entrenamiento estable y un escenario de producción
    con datos 'contaminados' (drift).
    """
    # --- Parámetros aleatorios para la generación ---
    n_features = np.random.randint(5, 15)
    n_train = np.random.randint(500, 1000)
    n_prod = np.random.randint(100, 200)

    # Crear nombres de columnas aleatorios
    cols = [f"feature_{i}" for i in range(n_features)]

    # --- Generación de Datos (INPUT) ---
    # Datos de entrenamiento: Distribución normal estándar
    train_data = np.random.randn(n_train, n_features)
    train_df = pd.DataFrame(train_data, columns=cols)

    # Datos de producción: 90% normales, 10% con "drift" (valores extremos)
    prod_data = np.random.randn(n_prod, n_features)
    n_anomalies = int(n_prod * 0.1)
    # Inyectamos drift multiplicando por un factor de escala y sumando un bias
    prod_data[:n_anomalies] = (prod_data[:n_anomalies] * 5) + 10

    # Introducir algunos NaNs aleatorios para probar la interpolación lineal
    for df in [train_df, pd.DataFrame(prod_data, columns=cols)]:
        for _ in range(5):
            df.iloc[np.random.randint(0, len(df)), np.random.randint(0, n_features)] = np.nan

    production_df = pd.DataFrame(prod_data, columns=cols)

    # Diccionario de entrada
    input_dict = {
        "train_df": train_df,
        "production_df": production_df
    }

    # --- Cálculo del Resultado Esperado (OUTPUT) ---
    # 1. Limpieza (Interpolación)
    train_clean = train_df.interpolate(method='linear').bfill().ffill()
    prod_clean = production_df.interpolate(method='linear').bfill().ffill()

    # 2. Escalamiento
    scaler = StandardScaler()
    train_scaled = scaler.fit_transform(train_clean)
    prod_scaled = scaler.transform(prod_clean)

    # 3. PCA (95% varianza)
    pca = PCA(n_components=0.95)
    pca.fit(train_scaled)

    # 4. Error de reconstrucción en Entrenamiento
    train_reconstructed = pca.inverse_transform(pca.transform(train_scaled))
    train_errors = np.linalg.norm(train_scaled - train_reconstructed, axis=1)

    # 5. Definir Umbral (Percentil 99)
    threshold = np.percentile(train_errors, 99)

    # 6. Error de reconstrucción en Producción
    prod_reconstructed = pca.inverse_transform(pca.transform(prod_scaled))
    prod_errors = np.linalg.norm(prod_scaled - prod_reconstructed, axis=1)

    # 7. Filtrar anomalías
    expected_output = production_df[prod_errors > threshold]

    return input_dict, expected_output

# Ejemplo de uso:
# input_data, expected_result = generar_caso_de_detect_data_drift()
# print(f"Filas en producción: {len(input_data['production_df'])}")
# print(f"Anomalías detectadas esperadas: {len(expected_result)}")
