# -*- coding: utf-8 -*-
"""question-0004-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggtdTpdYdIK6Dz51b0aqC_K3uMS8xOw9

**question-0004-usecase-generator**
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def generar_caso_de_detectar_anomalias_energia():
    """
    Genera casos de prueba aleatorios para la función detectar_anomalias_energia.
    """
    # 1. COMPONENTE ALEATORIO: Definir tamaño y ruido
    n_rows = np.random.randint(500, 1000)
    noise_level = np.random.uniform(0.1, 0.5)
    num_anomalies = np.random.randint(5, 15)

    # 2. CREACIÓN DEL INPUT (Datos sintéticos)
    fechas = [datetime(2024, 1, 1) + timedelta(hours=i) for i in range(n_rows)]

    # Crear un patrón senoidal (día/noche) + ruido
    t = np.linspace(0, 4 * np.pi * (n_rows/24), n_rows)
    consumo = 50 + 20 * np.sin(t) + np.random.normal(0, noise_level, n_rows)

    # Inyectar anomalías aleatorias (picos de consumo)
    indices_anomalias = np.random.choice(range(n_rows), size=num_anomalies, replace=False)
    consumo[indices_anomalias] *= np.random.uniform(2.0, 5.0)

    df_input = pd.DataFrame({
        'timestamp': fechas,
        'consumo_kwh': consumo
    })

    # El input solicitado como diccionario de argumentos
    input_dict = {"df_consumo": df_input}

    # 3. CREACIÓN DEL OUTPUT (Estructura esperada)
    # El output esperado debe ser el DF original con la columna booleana y el ratio
    df_output_mock = df_input.copy()

    # Simulamos la columna 'es_anomalia' (que creará tu función)
    # Nota: Ponemos valores por defecto ya que el valor real dependerá del modelo
    df_output_mock['es_anomalia'] = False

    # El output esperado es una tupla: (DataFrame, float)
    expected_ratio_placeholder = float(num_anomalies / (n_rows * 0.2)) # Estimación lógica

    output_tuple = (df_output_mock, expected_ratio_placeholder)

    return input_dict, output_tuple

# Ejemplo de uso:
input_data, output_data = generar_caso_de_detectar_anomalias_energia()
print(f"Filas generadas: {len(input_data['df_consumo'])}")
print(f"Columnas en el output esperado: {list(output_data.columns)}")
